### ISSUE TITLE
Give me push access :)

### ISSUE THREAD

**Issue by pablox-cl** [powerline/pkg-archlinux#1]
Hi!

Since a couple of months, I have been the maintainer of these packages in the AUR (https://aur.archlinux.org/packages/?SeB=m&K=pablox), I think it would be better if I have access here too :)

**Comment by Lokaltog** [comment]
I've never used the teams functionality on Github, but I've added you to a team with admin access to this repo, let me know if it works properly!

**Comment by pablox-cl** [comment]
Well, I was thinking is being a collaborator actually, but I guess is the same purpose. I accepted the invitation. Thanks!
